######################################################################
# Automatically generated by qmake (3.0) qui jun 12 01:43:38 2014
######################################################################

QT += testlib
TEMPLATE = app
TARGET = cacic-agente
INCLUDEPATH += .

# Input
HEADERS += testinstallcacic.h
SOURCES += testinstallcacic.cpp
